### ISSUE TITLE
[Meta]: find and triage remaining asserts in the codebase

### ISSUE THREAD

**Issue by caveman99** [meshtastic/firmware#2105]
Asserts are like pulling a handbrake mid corner. Handle them gracefully instead and allow the firmware to continue. This meta issue keeps track of the remaining asserts in the code.

- [x] mesh/Channels.cpp:194:    assert(chIndex < channelFile.channels_count); // This should be equal to MAX_NUM_CHANNELS
- [x] mesh/PhoneAPI.cpp:302:        assert(0); // unexpected state - FIXME, make an error code and reboot
- [x] mesh/PhoneAPI.cpp:372:        assert(0); // unexpected state - FIXME, make an error code and reboot
- [x] mesh/RadioInterface.cpp:167:    assert(p->which_payload_variant == MeshPacket_encrypted_tag); // It should have already been encoded by now
- [x] mesh/RadioInterface.cpp:176:    assert(slotTimeMsec); // Better be non zero
- [x] mesh/RadioInterface.cpp:273:    assert(sizeof(PacketHeader) == 16); // make sure the compiler did what we expected
- [x] mesh/RadioInterface.cpp:403:            assert(0); // Unknown enum
- [x] mesh/RadioInterface.cpp:425:    assert(myRegion); // Should have been found in init
- [x] mesh/RadioInterface.cpp:492:    assert(!sendingPacket);
- [x] mesh/RadioInterface.cpp:495:    assert(p->which_payload_variant == MeshPacket_encrypted_tag); // It should have already been encoded by now
- [x] mesh/RadioInterface.cpp:505:    assert(p->hop_limit <= HOP_MAX);
- [x] mesh/RadioInterface.cpp:509:    assert(h->from);
- [x] mesh/RadioLibInterface.cpp:231:                        assert(txp);
- [x] mesh/RadioLibInterface.cpp:244:            assert(0); // We expected to receive a valid notification from the ISR
- [x] mesh/RadioLibInterface.cpp:362:                assert(HOP_MAX <= PACKET_FLAGS_HOP_MASK); // If hopmax changes, carefully check this code
- [x] mesh/RadioLibInterface.cpp:369:                assert(((uint32_t)payloadLen) <= sizeof(mp->encrypted.bytes));
- [x] mesh/ReliableRouter.cpp:151:        assert(numErased == 1);
- [x] mesh/ReliableRouter.cpp:226:    assert(iface);
- [x] mesh/Router.cpp:97:    assert(sizeof(PacketId) == 4 || sizeof(PacketId) == 1);                // only supported values
- [x] mesh/Router.cpp:194:    assert(p->to != nodeDB.getNodeNum()); // should have already been handled by sendLocal
- [x] mesh/Router.cpp:222:    assert(p->which_payload_variant == MeshPacket_encrypted_tag ||
- [x] mesh/Router.cpp:273:    assert(iface); // This should have been detected already in sendLocal (or we just received a packet from outside)
- [x] mesh/Router.cpp:338:            assert(rawSize <= sizeof(bytes));
- [x] mesh/TypedQueue.h:24:        assert(h);
- [x] modules/AdminModule.cpp:45:    assert(r);
- [x] modules/CannedMessageModule.cpp:552:    assert(req.decoded.want_response);
- [x] modules/esp32/StoreForwardModule.cpp:417:            assert(0); // unexpected state - FIXME, make an error code and reboot
- [x] modules/ExternalNotificationModule.cpp:350:    assert(req.decoded.want_response);
- [x] modules/PositionModule.cpp:59:    assert(node->has_position);
- [x] modules/ReplyModule.cpp:6:#include <assert.h>
- [x] modules/ReplyModule.cpp:10:    assert(currentRequest); // should always be !NULL
- [x] modules/RoutingModule.cpp:27:    assert(currentRequest);
- [x] modules/RoutingModule.cpp:31:        assert(0); // 1.2 refactoring fixme, Not sure if anything needs this yet?
- [x] modules/TraceRouteModule.cpp:64:    assert(currentRequest);
- [x] mqtt/MQTT.cpp:133:        assert(!mqtt);
- [x] platform/esp32/ESP32CryptoEngine.cpp:33:            assert(!res);
- [x] platform/esp32/ESP32CryptoEngine.cpp:51:            assert(numBytes <= MAX_BLOCKSIZE);
- [x] platform/esp32/ESP32CryptoEngine.cpp:57:            assert(!res);
- [x] platform/portduino/CrossPlatformCryptoEngine.cpp:59:            assert(numBytes <= MAX_BLOCKSIZE);
- [x] platform/portduino/SimRadio.cpp:169:                    assert(txp);
- [x] platform/portduino/SimRadio.cpp:184:        assert(0); // We expected to receive a valid notification from the ISR
- [x] platform/portduino/SimRadio.cpp:233:    assert(isReceiving);
- [x] sleep.cpp:160:            assert(0); // FIXME - for now we just restart, need to fix bug #167

**Comment by caveman99** [comment]
Note: the line numbers are against develop ...

**Comment by caveman99** [comment]
did anybody test the cleanup artefcts from #2106 ?
