### ISSUE TITLE
[Bug]: Tracking issue for cross network Channel and DM's

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#2406]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

2.1.6

### Description

Issue to track things we find about the new cross network node info channel functionality enabling DM's on shared channels.

### Help Test

You can help test this new functionality by:

* Creating a new two channel QR code, set up a few devices with that code
* Use the iOS app to share only the secondary channel from share channels with a couple of other nodes
* Communicate across networks on the shared secondary channel from the first network, including DM's

### Current Issues

* [ ] Android Testing Needed
* [ ] Channel Messages work in the webui, but node info is empty and dm's don't work
* [x] Need to add an indicator to the node list on iOS if a node is from a channel > 0  
* [ ] MQTT Seems to crash much more frequently

**Comment by garthvh** [comment]
![IMG_0649](https://user-images.githubusercontent.com/1795163/229389249-105f7b88-e854-4f24-808b-276ceac49622.PNG)

**Comment by thebentern** [comment]
@garthvh do we need to keep this issue open? Some of this is being tracked in other tickets.
